version: 2.1
workflows:
  main:
    jobs:
      - build
      - lint
      - deploy:
          filters:
            branches:
              only:
                - CD
          requires:
            - build
            - lint

job-references:
  node_env: &node_env
    docker:
      - image: circleci/node:latest

  restore_npm: &restore_npm
    keys:
      - node-v1-{{ checksum "package.json" }}
      - node-v1-

  install_npm: &install_npm
    name: "Install NPM dependencies"
    command: npm ci

  save_npm: &save_npm
    key: node-v1-{{ checksum "package.json" }}
    paths:
       node_modules

jobs:
  build:
    <<: *node_env
    steps:
      - checkout
      - restore_cache: *restore_npm
      - run: *install_npm
      - save_cache: *save_npm
      - run:
          name: "Build"
          command: npm run build
      - run:
          name: "Check output exists"
          command: "[ -s lib/index.js ]"
      - persist_to_workspace:
          root: lib
          paths:
            - "*"

  lint:
    <<: *node_env
    steps:
      - checkout
      - restore_cache: *restore_npm
      - run: *install_npm
      - save_cache: *save_npm
      - run:
          name: "Lint"
          command: npm run lint

  deploy:
    <<: *node_env
    steps:
      - checkout
      - restore_cache: *restore_npm
      - run: *install_npm
      - save_cache: *save_npm
      - attach_workspace:
          at: lib
      - run:
          name: "Deploy"
          command: |
            echo $GH_REPO
            npx sync-glitch-cli
